<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container9l6mcsn\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container9l6mcsn/appProdProjectContainer.php') {
    touch(__DIR__.'/Container9l6mcsn.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\Container9l6mcsn\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \Container9l6mcsn\appProdProjectContainer([
    'container.build_hash' => '9l6mcsn',
    'container.build_id' => '5cd1524c',
    'container.build_time' => 1636655745,
], __DIR__.\DIRECTORY_SEPARATOR.'Container9l6mcsn');
