<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHoqkmbp\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHoqkmbp/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerHoqkmbp.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerHoqkmbp\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerHoqkmbp\appProdProjectContainer([
    'container.build_hash' => 'Hoqkmbp',
    'container.build_id' => 'a1b69340',
    'container.build_time' => 1636757368,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHoqkmbp');
