<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRc9je6c\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRc9je6c/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerRc9je6c.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerRc9je6c\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerRc9je6c\appProdProjectContainer([
    'container.build_hash' => 'Rc9je6c',
    'container.build_id' => '048a452b',
    'container.build_time' => 1636383861,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRc9je6c');
