<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBzi2k69\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBzi2k69/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerBzi2k69.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerBzi2k69\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerBzi2k69\appProdProjectContainer([
    'container.build_hash' => 'Bzi2k69',
    'container.build_id' => '8daa454f',
    'container.build_time' => 1636383867,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBzi2k69');
