<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFxarwd4\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFxarwd4/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerFxarwd4.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerFxarwd4\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerFxarwd4\appProdProjectContainer([
    'container.build_hash' => 'Fxarwd4',
    'container.build_id' => 'd82571f3',
    'container.build_time' => 1636757372,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFxarwd4');
